[tool.ruff]
line-length = 79
extend-exclude = [".pfnci", "cupy"]

[tool.ruff.lint]
select = ["Q", "E", "F", "W", "UP", "I002", "FA", "PYI", "PLC01"]

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"

[tool.mypy]
files = ["builder/*.py", "verifier/*.py", "*.py"]
strict = true
ignore_missing_imports = true

[tool.autopep8]
exclude = "cupy"
