configs {
  key: "cupy-release-tools"
  value {
    requirement {
      cpu: 8
      gpu: 1
      memory: 48
      disk: 30
    }
    time_limit {
      seconds: 7200
    }
    command: "sh .pfnci/wheel-linux/main.sh 3.8.0 11.4 master"
  }
}
configs {
  key: "cupy-release-tools.linux.rocm"
  value {
    requirement {
      cpu: 8
      memory: 36
      disk: 30
    }
    time_limit {
      seconds: 7200
    }
    command: "sh .pfnci/wheel-linux/main.sh 3.8.0 rocm-4.2 master"
    environment_variables { key: "CUPY_RELEASE_SKIP_VERIFY" value: "1" }
  }
}
configs {
  key: "cupy-release-tools.win"
  value {
    requirement {
      cpu: 8
      gpu: 1
      memory: 12
      disk: 30
      image: "windows"
    }
    time_limit {
      seconds: 7200
    }
    command: ".pfnci\\wheel-windows\\main.bat 3.9.0 11.4 master"
  }
}
configs {
  key: "cupy-wheel-win"
  value {
    requirement {
      cpu: 8
      gpu: 1
      memory: 12
      disk: 30
      image: "windows"
    }
    time_limit {
      seconds: 7200
    }
    command: ".pfnci\\wheel-windows\\main.bat 3.9.0 10.2 master"
  }
}
configs {
  key: "cupy-wheel-linux"
  value {
    requirement {
      cpu: 8
      gpu: 1
      memory: 48
      disk: 30
    }
    time_limit {
      seconds: 7200
    }
    command: ".pfnci/wheel-linux/main.sh 3.9.0 11.2 master"
  }
}
