configs {
  key: "cupy-release-tools"
  value {
    requirement {
      cpu: 2
      gpu: 1
      memory: 12
      disk: 30
    }
    time_limit {
      seconds: 3600
    }
    command: "sh .pfnci/test.sh"
  }
}
configs {
  key: "cupy-wheel-win"
  value {
    requirement {
      cpu: 2
      gpu: 1
      memory: 8
      disk: 30
      image: "windows"
    }
    time_limit {
      seconds: 3000
    }
    command: ".pfnci\\wheel-windows\\main.bat 3.7.0 9.0 origin/master"
  }
}
