#!/bin/bash

# ROCm
if [ -d /opt/rocm ]; then
  export ROCM_HOME="/opt/rocm"
  export CUPY_INSTALL_USE_HIP=1
fi

export CUPY_NUM_BUILD_JOBS=4
export CUPY_NUM_NVCC_THREADS=4

export LDFLAGS="-Wl,--as-needed ${LDFLAGS}"

"$@"
