name: "Pre-review Tests"

on: [push, pull_request]

jobs:
  pretest:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install
        run: |
          pip install -U pip wheel
          pip install -r requirements.txt
          pip install pre-commit

      - name: run pre-commit
        run: |
          pre-commit run -a --show-diff-on-failure
