name: "Pre-review Tests"

on: [push, pull_request]

jobs:
  pretest:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: install
      run: |
        pip install -U pip wheel
        pip install -r requirements.txt
        pip install ruff autopep8 mypy

    - name: ruff
      run: |
        ruff check

    - name: autopep8
      run: |
        autopep8 -r . --global-config .pep8 --diff | tee check_autopep8
        test ! -s check_autopep8

    - name: mypy
      run: |
        mypy
